#!/usr/bin/python

import getpass
import os
import sys
import webbrowser
from string import whitespace

if not sys.stdin.isatty():
	for line in sys.stdin:
		line = str(line)
		qString = line.replace(" ","+")
		qString = qString.translate(None, whitespace)
		stdQuery = 'https://www.google.com/#q=' + qString
		savout = os.dup(1)
		os.close(1)
		os.open(os.devnull, os.O_RDWR)
		try:
			webbrowser.open(stdQuery)
		finally:
			os.dup2(savout, 1)

elif len(sys.argv) < 2:
	try:
		user = getpass.getuser()
	except:
		user = 'friend'
		helloDave = 'Hello ' + user + ', what would you like to know?' 
	else:
		helloDave = 'Hello ' + user + ', what would you like to know?' 
	print helloDave

elif len(sys.argv) >= 2:
	allArgs = sys.argv[1:]
	catArgs = '+'.join(allArgs)
	urlQuery = 'https://www.google.com/#q=' + catArgs
	savout = os.dup(1)
	os.close(1)
	os.open(os.devnull, os.O_RDWR)
	try:
		webbrowser.open(urlQuery)
	finally:
		os.dup2(savout, 1)

sys.exit()