#!/usr/bin/env python
#Version 0.0.2 Adam Taranto, February 2015
#Contact, Adam Taranto, adam.taranto@anu.edu.au

import getpass
import hashlib
import os
from string import whitespace
import sys
import webbrowser

def parlae(question):
	if hashlib.md5(question.encode('utf-8')).hexdigest() == '1a1dc91c907325c69271ddf0c944bc72':
		sys.exit(0)
	else:
		pass

def run_search(question,noExit=False):
	urlQuery = 'http://lmgtfy.com/?q=' + question
	savout = os.dup(1)
	os.close(1)
	os.open(os.devnull, os.O_RDWR)
	try:
		webbrowser.open(urlQuery)
	finally:
		os.dup2(savout, 1)
	if not noExit:
		sys.exit(0)

if not sys.stdin.isatty(): #True if no stdin
	for line in sys.stdin:
		line = str(line)
		qString = line.replace(" ","+")
		qString = qString.translate(None, whitespace)
		run_search(qString,noExit=True)
	sys.exit(0)

if len(sys.argv) < 2:
	try:
		user = getpass.getuser()
	except:
		user = 'friend'
		helloDave = 'Hello ' + user + ', what would you like to know? ' 
	else:
		helloDave = 'Hello ' + user + ', what would you like to know? ' 
	try: 
		input == raw_input 	#Check if in python3
		question = raw_input(helloDave)
		question = question.split()
	except NameError:
		question = input(helloDave)
		question = question.split()
	parlae(question)
	run_search('+'.join(question))

elif len(sys.argv) >= 2:
	question = sys.argv[1:]
	run_search('+'.join(question))